# Generated by Django 3.1.3 on 2021-01-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='read_count',
            field=models.IntegerField(default=0),
        ),
    ]
