# Generated by Django 3.1.3 on 2021-02-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_recomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='badcomment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recomment',
            name='badcomment',
            field=models.IntegerField(default=0),
        ),
    ]
