# Generated by Django 3.1.3 on 2021-02-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210204_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='club_pk',
            field=models.IntegerField(default=0),
        ),
    ]
