# Generated by Django 3.1.3 on 2021-02-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_comment_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='post_cnt',
            field=models.IntegerField(default=1),
        ),
    ]
