# Generated by Django 3.1.3 on 2021-02-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_hashtag_post_cnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='opinion_type',
            field=models.IntegerField(default=0),
        ),
    ]
