# Generated by Django 3.1.3 on 2021-02-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20210206_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='agree_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='disagree_count',
            field=models.IntegerField(default=0),
        ),
    ]
