# Generated by Django 3.1.3 on 2021-02-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20210206_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='opinion_type',
            field=models.BooleanField(),
        ),
    ]
