# Generated by Django 3.1.3 on 2021-02-06 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_recomment_emotion'),
        ('articles', '0010_auto_20210206_1810'),
    ]

    operations = [
    ]
