# Generated by Django 3.1.3 on 2021-02-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20210206_1759'),
        ('articles', '0011_recomment_emotion'),
    ]

    operations = [
    ]
