# Generated by Django 3.1.3 on 2021-02-07 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20210206_2214'),
        ('articles', '0014_merge_20210207_1444'),
    ]

    operations = [
    ]
