# Generated by Django 3.1.3 on 2021-02-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_merge_20210207_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='clubname',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
