# Generated by Django 3.1.3 on 2021-02-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_article_clubname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='clubname',
            field=models.CharField(default='', max_length=150),
        ),
    ]
