# Generated by Django 3.1.3 on 2021-02-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20210127_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_article',
            name='category',
            field=models.CharField(default='health', max_length=50),
            preserve_default=False,
        ),
    ]
