# Generated by Django 3.1.3 on 2021-02-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_club_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_article',
            name='url',
            field=models.CharField(max_length=150),
        ),
    ]
