# Generated by Django 3.1.3 on 2021-02-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20210207_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_member',
            name='article_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='club_member',
            name='comment',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club_member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2021-02-07'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club_member',
            name='signdate',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club_member',
            name='visit_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='club_member',
            name='visitdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
