# Generated by Django 3.1.3 on 2021-02-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_auto_20210207_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_member',
            name='signdate',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
