# Generated by Django 3.1.3 on 2021-02-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_auto_20210207_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_member',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
