# Generated by Django 3.1.3 on 2021-02-10 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_auto_20210207_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club_article_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('decription', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=150)),
                ('video', models.CharField(max_length=150)),
                ('Club_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club_article')),
            ],
        ),
    ]
