# Generated by Django 3.1.3 on 2021-02-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_club_article_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_article_info',
            name='decription',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='club_article_info',
            name='image',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='club_article_info',
            name='site_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='club_article_info',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='club_article_info',
            name='video',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
