# Generated by Django 3.1.3 on 2021-02-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_auto_20210210_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_article',
            name='decription',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='club_article',
            name='image',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='club_article',
            name='site_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='club_article',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='club_article',
            name='video',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.DeleteModel(
            name='Club_article_info',
        ),
    ]
