# Generated by Django 3.1.3 on 2021-01-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210120_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='token',
            field=models.CharField(default=1234, max_length=10),
            preserve_default=False,
        ),
    ]
