# Generated by Django 3.1.3 on 2021-02-07 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210206_2325'),
        ('accounts', '0006_auto_20210206_2324'),
    ]

    operations = [
    ]
