# Generated by Django 3.1.3 on 2021-02-07 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210206_2212'),
        ('accounts', '0007_merge_20210207_1444'),
    ]

    operations = [
    ]
