# Generated by Django 3.1.3 on 2021-02-07 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_20210207_1817'),
        ('accounts', '0008_merge_20210207_1905'),
    ]

    operations = [
    ]
