# Generated by Django 3.1.3 on 2021-02-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alarm_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='object_content',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
