<<<<<<< HEAD
# Generated by Django 3.1.3 on 2021-02-15 08:22
=======
# Generated by Django 3.1.3 on 2021-02-15 07:25
>>>>>>> ece44d53f63776b7665ffb6ef5948396cdf7d8d9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alarm_object_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
