<<<<<<< HEAD
# Generated by Django 3.1.3 on 2021-02-15 07:30
=======
# Generated by Django 3.1.3 on 2021-02-15 07:25
>>>>>>> 369f901c854b9b3aa60c0c2fb4c20848d8c18d2f

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alarm_object_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
