# Generated by Django 3.1.3 on 2021-02-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_auto_20210215_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='start',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
