# Generated by Django 3.1.3 on 2021-02-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='publishTime',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
